### ISSUE TITLE
"Fontconfig error: No writable cache directories" + GUI does not load

### ISSUE THREAD

**Issue by mattfbacon** [FontManager/font-manager#287]
When running font-manager, the message "Fontconfig error: No writable cache directories" is spammed in the console hundreds of times, and the GUI loads the basic layout but not any of the actual content.

### Reproduce

1. Run font-manager (in terminal to see stdout)

### Screenshot

![Terminal showing messages and Font-Manager not loading](https://imgur.com/knAcP0O.png)

### System Info

 - OS: Arch Linux
 - Desktop Environment: i3
 - Font Manager version: 0.8.8
 - Font Manager installation method: Distribution package

### Additional context

Fonts work properly on the system. Fontconfig is not broken.

**Comment by JerryCasiano** [comment]
That message is expected because we call FcEnableHome. It shouldn't have any adverse effects as we only disable home temporarily during loading so that that Fontconfig includes disabled fonts in the results.

So that in and of itself isn't helpful in determining why the interface fails to load on your system. 

Unfortunately I don't have an Arch installation at this time to test with so we'll have to wait a bit and see if other Arch users have the same issue or if this is something that only happens on certain configurations.


![Screenshot from 2022-02-25 01-08-53](https://user-images.githubusercontent.com/11490124/155664658-39c620a6-8d24-444c-856e-b695ab943468.png)

If it doesn't affect Arch users across the board then it's unlikely I'd be able to reproduce it on a fresh installation anyway.

**Comment by mattfbacon** [comment]
I forgot to mention, the GUI is also completely unresponsive. The window does not resize properly or respond to input and must be killed with Ctrl-C in the terminal.

**Comment by JerryCasiano** [comment]
As I said previously unless other Arch users are experiencing the same issue it's unlikely this issue will receive much attention.

I suggest asking on their forums to see if others can confirm. If you get confirmation, post a link.

Just to clarify, as far as the terminal spam goes, my previous comment wasn't intended to imply that it doesn't need to be fixed, it does and probably will be in the next release. It was just to point out that it's likely not the cause of the problem your experiencing.

Anyway, if you can get other users to confirm this issue is more likely to get some attention.

Sorry, but it is what is. We'll keep this open for a while, just in case.

**Comment by mattfbacon** [comment]
Are you not the main developer? What do you mean by "it's unlikely this issue will receive much attention"?

**Comment by JerryCasiano** [comment]
> Are you not the main developer? What do you mean by "it's unlikely this issue will receive much attention"?

I mean exactly that. I'm not sure what's unclear about that statement and given the context surrounding that statement and the suggestions you were given I don't see how it could be any clearer.

Unless you really think I'm going to download and install a distribution, which isn't even a point and click affair by the way, over a single report.

But that can't possibly be the case, right?

I mean that sounds silly just saying it...

**Comment by mattfbacon** [comment]
I didn't realize you thought I expected you to install Arch to reproduce it. No need to do that. I just wanted some help figuring out the source of the issue from the person that likely knows the code best.

To that end: Are there any blocking calls made in the UI thread that could cause the UI to hang?

**Comment by JerryCasiano** [comment]
At that point, the interface is just waiting for a list of fonts from Fontconfig and for the database update to signal it's complete.

BUT normally you would still be able to control the window, move it, close it, etc.

I have seen the call to Fontconfig take a few seconds depending on system state and amount of installed fonts but I've never seen it block completely or repeatedly.

It's possible the database update fails to complete. 

Make sure permissions in your ~/.cache and ~/.config directory are sane. 

Since the only errors in your terminal are from a library and at this point common to all installations...

I honestly have no clue where to start or any pointers to give. I would definitely have to be able to reproduce this locally to personally be able to do anything about it.

I'm sorry I just don't have anything more helpful than that.

**Comment by mattfbacon** [comment]
Thanks for the pointer. I've made those changes and I'm trying to build the project but I'm getting a strange error from Ninja (or rather samurai):

```
samu: job failed: /usr/bin/g-ir-scanner --no-libtool --namespace=Unicode --nsversion=0.8.8 --warn-all --output lib/unicode/Unicode-0.8.8.gir --c-include=unicode-info.h -I/run/media/matt/zdani/code/notmine/font-manager/lib/unicode -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/unicode -I/run/media/matt/zdani/code/notmine/font-manager/build/. -I/run/media/matt/zdani/code/notmine/font-manager/. -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/common -I/run/media/matt/zdani/code/notmine/font-manager/lib/common -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/orthographies -I/run/media/matt/zdani/code/notmine/font-manager/lib/orthographies -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/unicode -I/run/media/matt/zdani/code/notmine/font-manager/lib/unicode --filelist=/run/media/matt/zdani/code/notmine/font-manager/build/lib/unicode/libunicode.so.p/Unicode_0.8.8_gir_filelist --include=Pango-1.0 --include=Gdk-3.0 --include=Gtk-3.0 --cflags-begin '-DG_LOG_DOMAIN="[font-manager]"' '-DGETTEXT_PACKAGE="font-manager"' -DNOT_REPRODUCIBLE -DGDK_DISABLE_DEPRECATED -DGTK_ENABLE_DEPRECATED -I/run/media/matt/zdani/code/notmine/font-manager/build/. -I/run/media/matt/zdani/code/notmine/font-manager/. -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/common -I/run/media/matt/zdani/code/notmine/font-manager/lib/common -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/orthographies -I/run/media/matt/zdani/code/notmine/font-manager/lib/orthographies -I/run/media/matt/zdani/code/notmine/font-manager/build/lib/unicode -I/run/media/matt/zdani/code/notmine/font-manager/lib/unicode -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/libxml2 -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/run/media/matt/zdani/code/notmine/font-manager/build/lib/unicode --library unicode -L/usr/lib -lm -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgmodule-2.0 -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsqlite3 -lxml2 -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
samu: subcommands failed
```

Have you experienced this issue? If so, do you know of a solution?

PS Permissions are sane in `~/.config` and `~/.cache`. I also checked `~/.local/share/fonts` and it was fine too.

**Comment by JerryCasiano** [comment]
Looks related to gobect-introspection.

Not sure what package that would be in, but search for it.

**Comment by mattfbacon** [comment]
Nevermind, forgot to run meson again after installing gobject-introspection. Anyway, a clean build from the HEAD of development works correctly even with the lines not commented out.

Must be something wrong with my font-manager installation. I can't figure out what, though, because they're the same version.

**Comment by mattfbacon** [comment]
I build font-manager inside the Nix build system using this environment:

```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
	buildInputs = with pkgs; [
		vala
		meson
		yelp-tools
		icu
		gettext
		samurai
		glib
		freetype
		gtk3
		json-glib
		libxml2
		sqlite
		gobjectIntrospection
		(python3.withPackages (ps: with ps; [ pygobject3 ]))
		webkitgtk
		libsoup
		pkg-config
	];
}
```

The dynamic linker dependencies are indeed different, but all of the dependencies that Arch binary and my binary share are the same version. The ones that are present in one but not the other can be explained by various feature flags and/or debug vs release build.

I'll try to build the package without Nix.

**Comment by mattfbacon** [comment]
Building in the Arch Linux environment results in a working binary.

**Comment by opseter** [comment]
I have the same problem. But the difference is that my desktop environment is dwm. And even after reinstall my system,attempt to install through  disribution repository or build locally still doesn't work.

**Comment by JerryCasiano** [comment]
@opseter 

Unfortunately I don't really have anything helpful aside from the suggestions given above.

And we're back to a single report type of situation since the previous reporter had a successful build locally.

There's something about your system that is different than most others, not sure how to reproduce that unless you have an install script that would give the same result everytime.

Without being able to reproduce it's just shot in the dark guesswork. :-(

**Comment by opseter** [comment]
@JerryCasiano 
Today I try to test font-manager using  manjaro-gnome in Virtulbox.The result is same as before.
So I think if this is a more general case?

**Comment by JerryCasiano** [comment]
@opseter 

If it is then we should see other people reporting also. 

While the application isn't what one would call popular it does have a fair amount of users across distributions so I would expect to see more complaints.

**Comment by opseter** [comment]
@JerryCasiano 
I am sorry that I made a mistake.
Font-manager  works on my reinstalled physic machine but it takes few minutes to load GUI.
It used to load quickly ,but one day I found the unormal situation.

**Comment by L911P** [comment]
:thinking: I'm on nixos and I experience the same thing as OP reported and also opseter. For me the window is responsive, but the font list never populates. It sometimes *does*, but i have to close f-m and reopen it several times for it to work properly.

**Comment by mattfbacon** [comment]
BTW, font manager from arch repos works for me and has for a while, but it does print "no writable cache directories" about twenty or thirty times on startup.

**Comment by tarikgraba** [comment]
I see this issue is closed. Do not want to pollute the thread, just to indicate that I have a similar behavior on Debian 12 (font-manager 0.8.8-2), where the user log (journalctl) are polluted by a lot of messages about the cache directory.

```
org.gnome.FontManager[xxx]: Fontconfig error: No writable cache directories
```

**Comment by fishBone000** [comment]
I'm experiencing the same issue with exactly same behavior on Arch Linux, except that my console is spammed by like only 10 times instead of hundreds.
Btw, when running with root, Font Manager pops up an empty window border, and doesn't respond to close, except Ctrl-C on terminal. 
Terminal output:
`(font-manager:1294): [font-manager]-CRITICAL **: 00:32:43.411: ArchiveManager.vala:61: 1 : Error spawning command line “dbus-launch --autolaunch=0d59266167e74a37b38cbe964046ea76 --binary-syntax --close-stderr”: Child process exited with code 1`
When running `dbus-launch --autolaunch=0d59266167e74a37b38cbe964046ea76 --binary-syntax --close-stderr` manually:
`Autolaunch requested, but X11 support not compiled in.
Cannot continue.`
Not sure if it's related.

**Comment by mattfbacon** [comment]
`dbus-launch --autolaunch` makes me think of this section of the dbus-launch man page:

> If DBUS_SESSION_BUS_ADDRESS is not set for a process that tries to use D-Bus, by default the process will attempt to invoke dbus-launch with the --autolaunch option to start up a new session bus or find the existing bus address on the X display or in a file in ˜/.dbus/session-bus/ ...

So maybe you do not have a session bus and the app is trying and failing to create one?

**Comment by NinZeige** [comment]
I'm also using Arch Linux, and I try to use font-manager today, although it is in a "barely usable" state, I still want to share my issue because it's quite interesting. My situation is almost identical to @fishBone000's , except for one thing: after printing "Fontconfig error: No writable cache directories" in the command line and waiting for about 4 minutes, the font-manager window suddenly popped up and started working normally.
![Screenshot from 2023-09-27 22-53-05](https://github.com/FontManager/font-manager/assets/51020316/8dbd2321-ced6-457b-8ce6-bac334f53e50)

**Comment by joemaro** [comment]
Same here, after some minutes of freezing it comes alive ...

**Comment by mattfbacon** [comment]
I can confirm that the issue has returned. I get "No writable cache directories" exactly 37 times and then it hangs with an unpopulated interface exactly as I reported in the initial issue.

**Comment by mattfbacon** [comment]
@JerryCasiano can we re-open this issue as it is recurring?
